### ISSUE TITLE
Curse of Doom is not recording any DPS

### ISSUE THREAD

**Issue by JulianNorton** [wowsims/wotlk#977]
**Describe the bug**
Curse of Doom is not functioning as intended and gives zero dps.

**To Reproduce**
1. [go to  wowsims link](https://wowsims.github.io/wotlk/warlock/#eJztUk1IVFEUft9543TnkXKMgpur19skgnBnHgO6aV6tgjYDgbi0RS6ihUQLbTXOyloF0iJXQRs3A61EUio0/9JIlEb8ocCQRkQZhbbhue/Zus0sXPjBPZzzfeeec3+O5ytiMtSFu+jFAJWAl8A70CdgFagBd64p+NQOgy5EKNosjANXnLZKUxnp4uMHQw+fqEus2hbgMe/vkv76g4L03Ay9/U1ehv/sUOBuTZLXzEcifhHRtUoz722QfnXiJirzoajzz2Xrh0k6FqaFa5Kwtk1BShhH4gPJ2Ki4Z3GGj6ellvie4vo06fKc9Y7Eq1Vcqf9Ttu/8667421Qcein++N7a+pRlV4Rd2LZxdcLaNxMUXFXxdYup3qY+GoQ8ygjQsUjOBRqCZ0qBSdMAHmnvMrua/GS+SMYqLRo0vcDNThOGWWNCI6vT5HMmzGXFxmw+G4b5XGjCfHYXWlWXiTf3SH9fJr+8Tu1/18gMr1MNqTrcMThbcIJRNxN3L/VErck5bkXXx15bLBW6E2a1cKM/RrWQ+0X+fU3n9tufRo2oUlr6/J869xrSxyJ545HZ6PYZEfXhFNaJhF0=)
2. Simulate
3. Check the detailed results to see curse of doom giving zero dps.

**Expected behavior**
Curse of doom DPS should be recorded.

**Additional context**

**Comment by JulianNorton** [comment]
![Screen Shot 2022-09-02 at 1 37 06 PM](https://user-images.githubusercontent.com/2412992/188208041-9c53b2bd-4602-4965-b13b-92b52f7649c3.png)

**Comment by PANDAxBEARS** [comment]
My guess is that there's a bug with how the details tab is aggregating the damage from CoD across multiple iterations. Changing iterations to 1 in the sim shows the correct DPS contribution for CoD, and as the # of iterations increases the DPS goes to 0.

**Comment by lologarithm** [comment]
this looks like it was fixed sometime in the last week or two (CoD is showing damage in live sim now)

**Comment by Tharre** [comment]
This is still an issue (and the link in the first message still reproduces it). It only happens at specific fight lengths and is related to the rotation code bugging out and stopping casting CoD after the first iteration.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1724 fixed
